apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: road-events-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rickdevma100/road-events-helm-charts.git
    targetRevision: main
    path: charts/road-events
  destination:
    server: https://kubernetes.default.svc
    namespace: road-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
